<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy - StrokeCare</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: white;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        h1, h2, h3 {
            color: #333;
        }
        p, ul, li {
            color: #555;
            line-height: 1.6;
        }
        ul {
            margin-left: 20px;
        }
        li {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>

<div class="container">
    <h1>Privacy Policy</h1>
    <p>Welcome to StrokeCare, a medical application designed to assist doctors in managing stroke rehabilitation. This Privacy Policy explains how we collect, use, and protect your personal data when you use our service.</p>

    <h2>Interpretation and Definitions</h2>

    <h3>Interpretation</h3>
    <p>Words with initial letters capitalized have meanings defined under the following conditions. These definitions apply whether the terms appear in singular or plural form.</p>

    <h3>Definitions</h3>
    <ul>
        <li><strong>Account:</strong> A unique account created for You to access our Service or parts of it.</li>
        <li><strong>Affiliate:</strong> An entity controlling, controlled by, or under common control with a party.</li>
        <li><strong>Application:</strong> Refers to StrokeCare, the software provided by the Company.</li>
        <li><strong>Company:</strong> Refers to StrokeCare.</li>
        <li><strong>Country:</strong> Tamil Nadu, India.</li>
        <li><strong>Device:</strong> Any device capable of accessing the Service, such as a computer, cellphone, or tablet.</li>
        <li><strong>Personal Data:</strong> Any information relating to an identified or identifiable individual.</li>
        <li><strong>Service:</strong> The Application.</li>
        <li><strong>Service Provider:</strong> Any person or entity processing data on behalf of the Company.</li>
        <li><strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service or from the Service infrastructure.</li>
        <li><strong>You:</strong> The individual or entity accessing or using the Service.</li>
    </ul>

    <h2>Collecting and Using Your Personal Data</h2>

    <h3>Types of Data Collected</h3>

    <h4>Personal Data</h4>
    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
    <ul>
        <li>Email address</li>
        <li>First name and last name</li>
    </ul>

    <h4>Usage Data</h4>
    <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device's IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data. When accessing the Service via a mobile device, additional information such as device type, unique ID, IP address, operating system, and browser type may also be collected.</p>

    <h4>Information Collected while Using the Application</h4>
    <p>While using Our Application, we may collect, with Your prior permission:</p>
    <ul>
        <li>Pictures and other information from your Device's camera and photo library. This information may be uploaded to the Company's servers and/or a Service Provider's server or it may be stored on Your device.</li>
    </ul>
    <p>You can enable or disable access to this information at any time through Your Device settings.</p>

    <h2>Sharing Your Personal Data</h2>
    <ul>
        <li><strong>With Service Providers:</strong> To monitor and analyze the use of our Service, and to contact You.</li>
        <li><strong>For Business Transfers:</strong> During mergers, sales, or acquisitions.</li>
        <li><strong>With Affiliates:</strong> Including our parent company and other subsidiaries under common control.</li>
        <li><strong>With Business Partners:</strong> To offer products, services, or promotions.</li>
        <li><strong>With Other Users:</strong> When interacting publicly or sharing personal information.</li>
        <li><strong>With Your Consent:</strong> For any other purpose with your explicit consent.</li>
    </ul>

    <h2>Retention of Your Personal Data</h2>
    <p>We will retain Your Personal Data only for as long as necessary to fulfill the purposes outlined in this Privacy Policy, and to comply with legal obligations. Usage Data will generally be retained for a shorter period, except when used to improve service functionality or for legal compliance.</p>

    <h2>Transfer of Your Personal Data</h2>
    <p>Your data may be processed and maintained on computers located outside of your jurisdiction. Your consent to this Privacy Policy signifies agreement to such transfers. We will ensure adequate security measures are in place for any such data transfers.</p>

    <h2>Disclosure of Your Personal Data</h2>

    <h4>Business Transactions</h4>
    <p>Your data may be transferred in case of mergers, acquisitions, or asset sales. We will notify you before such data is transferred.</p>

    <h4>Law Enforcement</h4>
    <p>We may disclose your data if required by law or in response to valid requests from public authorities.</p>

    <h4>Other Legal Requirements</h4>
    <p>We may disclose your data to comply with legal obligations, protect our rights or property, prevent wrongdoing, protect safety, or defend against legal liability.</p>

    <h2>Security of Your Personal Data</h2>
    <p>We strive to protect your data but cannot guarantee absolute security. We use commercially acceptable methods to safeguard your Personal Data.</p>

    <h2>Children's Privacy</h2>
    <p>Our Service does not target individuals under 13. We do not knowingly collect data from this age group. If you are a parent or guardian and become aware of such data collection, please contact us.</p>

    <h2>Changes to this Privacy Policy</h2>
    <p>We may update this Privacy Policy and will notify you of any changes by posting the new policy on this page. We will also notify you via email or a prominent notice on our Service. Please review the policy periodically for updates.</p>

    <h2>Contact Us</h2>
    <p>If you have any questions about this Privacy Policy, you can contact us at <a href="mailto:enggadmission@gmail.com">enggadmission@gmail.com</a>.</p>

    <p>© 2024 StrokeCare. All rights reserved.</p>
</div>

</body>
</html>
